version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      ALLOWED_HOSTS: localhost
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
       - "db:/var/lib/postgresql/data"

volumes:
  db:
